name: gender_reveal_ipad_pro
description: Lokalna aplikacja na iPad do głosowania (gender reveal) z wieloma wykresami.
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  fl_chart: ^0.69.0
  uuid: ^4.5.0
  confetti: ^0.7.0
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true